INSERT INTO GENRE (NAME) VALUES ('Комедия');

INSERT INTO GENRE (NAME) VALUES ('Драма');

INSERT INTO GENRE (NAME) VALUES ('Мультфильм');

INSERT INTO GENRE (NAME) VALUES ('Триллер');

INSERT INTO GENRE (NAME) VALUES ('Документальный');

INSERT INTO GENRE (NAME) VALUES ('Боевик');

INSERT INTO MPA (NAME) VALUES ('G');

INSERT INTO MPA (NAME) VALUES ('PG');

INSERT INTO MPA (NAME) VALUES ('PG-13');

INSERT INTO MPA (NAME) VALUES ('R');

INSERT INTO MPA (NAME) VALUES ('NC-17');

