INSERT INTO GENRE (NAME) VALUES ('Комедия');

INSERT INTO GENRE (NAME) VALUES ('Драма');

INSERT INTO GENRE (NAME) VALUES ('Мультфильм');

INSERT INTO GENRE (NAME) VALUES ('Триллер');

INSERT INTO GENRE (NAME) VALUES ('Документальный');

INSERT INTO GENRE (NAME) VALUES ('Боевик');

INSERT INTO MPA (name) VALUES ('G');

INSERT INTO MPA (name) VALUES ('PG');

INSERT INTO MPA (name) VALUES ('PG-13');

INSERT INTO MPA (name) VALUES ('R');

INSERT INTO MPA (name) VALUES ('NC-17');

